version: "2"

services:
    app:
        build:
            context: docker
        ports:
            - "8888:80"
        depends_on:
            - db
        volumes:
            - .:/app
            - /app/var/cache
            - /app/var/sessions
            - ./docker/nginx.conf:/etc/nginx/nginx.conf

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - ./lib:/var/lib/mysql