<?xml version="1.0" encoding="ISO-8859-1"?>
<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
             xmlns:tns="urn:arnleadservicewsdl"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             targetNamespace="urn:gettokenservicewsdl">

    <types>
        <xsd:schema targetNamespace="urn:gettokenwsdl">
            <xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/" />
            <xsd:import namespace="http://schemas.xmlsoap.org/wsdl/" />
        </xsd:schema>
    </types>

    <message name="TokenRequest">
        <part name="name" type="xsd:string" />
    </message>

    <message name="TokenResponse">
        <part name="Token" type="xsd:string" />
    </message>

    <portType name="gettokenwsdlPortType">
        <operation name="GetToken">
            <documentation>GetToken service will return a SSO token.</documentation>
            <input message="tns:TokenRequest"/>
            <output message="tns:TokenResponse"/>
        </operation>
    </portType>

    <binding name="gettokenwsdlBinding" type="tns:gettokenwsdlPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="GetToken">
            <soap:operation soapAction="urn:arnleadservicewsdl#GetToken" style="rpc"/>

            <input>
                <soap:body use="encoded" namespace="urn:gettokenwsdl"
                           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </input>

            <output>
                <soap:body use="encoded" namespace="urn:gettokenwsdl"
                           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </output>
        </operation>
    </binding>

    <service name="gettokenwsdl">
        <port name="gettokenwsdlPort" binding="tns:gettokenwsdlBinding">
            <soap:address location="http://localhost:8888/soap" />
        </port>
    </service>
</definitions>